default:
  - VERSION
custom:
  IMAGE:
    type: string
    trim: true
    description: "Image Name"
  YOUR_CHOICE:
    type: choice
    choices: [ "a", "b", "c", "d" ]
    description: "Your choice"
  YOUR_PASSWORD:
    type: password
    description: "Password for host"