custom:
  VERSION:
    type: string
    trim: true
    description: "Build Version"
  IMAGE:
    type: string
    trim: true
    description: "Image Name"
  TYPE:
    type: choice
    choices: [ "a", "b", "c", "d" ]
    description: "Image Name"
