FROM jenkins/agent

USER root

# Install and configure docker
RUN curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
RUN apt update -y && apt install -y docker-ce docker-ce-cli containerd.io
RUN usermod -aG docker jenkins

USER root